### ISSUE TITLE
Play nicely with other gutters

### ISSUE THREAD

**Issue by oranj** [bradfeehan/SublimePHPCoverage#19]
I'm using [Kindari's XDebug](https://github.com/Kindari/SublimeXdebug), and it uses the gutter for notifications as well. This is causing a collision. Any way to separate these?)

![screen shot 2014-04-08 at 4 20 45 pm](https://cloud.githubusercontent.com/assets/1034204/2649471/bdf608fe-bf63-11e3-911f-06d240655ecc.png)

**Comment by bradfeehan** [comment]
Unfortunately, not really. Sublime doesn't have much flexibility in its UI, which is why I'm not surprised that the way I implemented the annotations collides with other extensions. I'm not aware of any way that it can be implemented differently.
