### ISSUE TITLE
ST2/ST3 inconsistency

### ISSUE THREAD

**Issue by mmdeas** [bradfeehan/SublimePHPCoverage#20]
According to the README, this plugin works with ST2 and ST3.
According to [Package Control](https://sublime.wbond.net/packages/PHP%20Code%20Coverage), it only works with ST2 and, as such, does not appear in ST3 Package Control.

**Comment by dustinnewbold** [comment]
I have the same issue. This does not show up for ST3 in package control.

**Comment by mmdeas** [comment]
I've been using it in ST3 and, as the README claims, it does work.
Having looked into the Package Control submission, I think the issue is probably that the schema version has been upgraded to 2.0 and this plugin uses 1.2.
When I get a moment, I'll rewrite it with the new schema and create a pull request.
