### ISSUE TITLE
Sublime PHP Coverage doesn't work on Sublime Text 3?

### ISSUE THREAD

**Issue by nguyentamgm** [bradfeehan/SublimePHPCoverage#25]
Hi there,

I'm using Sublime Text 3 (build 3103). I installed and configured your package and everything was fine. I tried to build with PHPUnit, there was no errors, and the clover.xml file was generated. But I don't see any coverage data in the margin (I'm using the default theme and colour form ST3).

Could you please let me know your ideas or any direction that I can take a look at?

Thank you very much!

**Comment by bradfeehan** [comment]
If you open the console with Ctrl + ` are there any errors?

**Comment by nguyentamgm** [comment]
Unfortunately, no errors, just a message about running PHPUnit command and "finished" message.

Here is my configuration (I configure in a Sublime project file)

`{
    "folders":
    [
        {
            "path": "public_html"
        }
    ],
        "settings": {
        "phpcoverage": {
            "report_path": "public_html/var/logs/clover.xml"
        }
    },
    "build_systems": [
        {
            "name": "PHPUnit",
            "working_dir": "$project_path/public_html",
            "cmd": [
                "vendor/bin/phpunit",
                "--coverage-clover",
                "var/logs/clover.xml"
            ]
        }
    ]
}`

I'm thinking about a reason that the project stored in a virtual machine running CentOS, and I am opening that project from my Mac, the source code is not stored locally on my computer.

**Comment by bradfeehan** [comment]
It's possible -- maybe the paths for the files in your `clover.xml` refer to paths inside the CentOS guest, which is different to the path on your Mac?

**Comment by bradfeehan** [comment]
I apologise that I won't be able to offer much assistance with this myself -- I've stopped using both PHP and Sublime Text since I created this project :sob:

**Comment by nguyentamgm** [comment]
Yeah no problems. I think it's the same problems with the GIT client apps, they can't work with the source code from network computers. Thanks for your support and I'll let you know if I have any update on this issue.
