### ISSUE TITLE
Watch the code coverage file for changes and update the editor

### ISSUE THREAD

**Issue by bradfeehan** [bradfeehan/SublimePHPCoverage#3]
Using inotify or something similar, watch the code coverage XML file for any changes, and automatically update the content of any open PHP files.

**Comment by bradfeehan** [comment]
Working on a solution to this which involves polling (bummer, but the only reliable cross-platform way).

**Comment by brodkin** [comment]
@bradfeehan Is there any way to support multiple watch methods depending on the filesystem and os?

**Comment by bradfeehan** [comment]
Sure, in theory, but it's quite a pain. I tried integrating [watchdog](https://github.com/gorakhargosh/watchdog), but it uses some C libraries which would need to be compiled for the target machine, and would require a Python egg for each OS. And then it falls back to polling, if there's nothing better available.

The polling solution is quite acceptable performance-wise, in practice it's just doing a `stat()` on most likely a single file (the coverage file) every 100ms, and that data will be cached by the OS in most cases... I don't think it's worth it.

**Comment by brodkin** [comment]
@bradfeehan That's fair.
